// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreSync.React.Server.DataAccess;

#nullable disable

namespace StoreSync.React.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoreSync.React.Server.Models.Price", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id", "DateCreated");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Id = "4902430453295",
                            DateCreated = new DateTime(2024, 5, 3, 11, 35, 55, 381, DateTimeKind.Local).AddTicks(2924),
                            Value = 8.0
                        },
                        new
                        {
                            Id = "7622300637996",
                            DateCreated = new DateTime(2024, 5, 3, 11, 35, 55, 381, DateTimeKind.Local).AddTicks(2936),
                            Value = 22.0
                        },
                        new
                        {
                            Id = "4800361410816",
                            DateCreated = new DateTime(2024, 5, 3, 11, 35, 55, 381, DateTimeKind.Local).AddTicks(2937),
                            Value = 13.0
                        });
                });

            modelBuilder.Entity("StoreSync.React.Server.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "4902430453295",
                            IsDeleted = false,
                            Name = "Downy",
                            Subtitle = "Garden Bloom"
                        },
                        new
                        {
                            Id = "7622300637996",
                            IsDeleted = false,
                            Name = "Tang",
                            Subtitle = "Grapes"
                        },
                        new
                        {
                            Id = "4800361410816",
                            IsDeleted = false,
                            Name = "Bear Brand",
                            Subtitle = "Swak"
                        });
                });

            modelBuilder.Entity("StoreSync.React.Server.Models.Purchase", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SaleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "SaleId");

                    b.HasIndex("SaleId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("StoreSync.React.Server.Models.Sale", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfPurchase")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("StoreSync.React.Server.Models.Price", b =>
                {
                    b.HasOne("StoreSync.React.Server.Models.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreSync.React.Server.Models.Purchase", b =>
                {
                    b.HasOne("StoreSync.React.Server.Models.Product", "Product")
                        .WithMany("Purchases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSync.React.Server.Models.Sale", "Sale")
                        .WithMany("Purchases")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("StoreSync.React.Server.Models.Product", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("StoreSync.React.Server.Models.Sale", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
